{% set name = "httpx2" %}
{% set version = "2.12.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7631fe9887a8a2275f4a2540e053aa670fcc50742864a9ae7c66e609fdcf12cf

build:
  skip: true # [py<310]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  entry_points:
    - httpx2 = httpx2:main

requirements:
  host:
    - hatch-fancy-pypi-readme
    - hatchling
    - pip
    - python
    - uv-dynamic-versioning >=0.8.0
  run:
    - python
    - truststore >=0.10
    - httpcore2 =={{ version }}
    - anyio >=4.10
    - idna >=3.18
    - typing_extensions >=4.5.0 # [py<313]
  run_constrained:
    # cli
    - click >=8.4.2
    - pygments ==2.*
    - rich >=10,<16
    # http2
    - h2 >=3,<5
    # socks
    - socksio 1.*
    # wsproto
    - wsproto>=1.2
    # zstd
    - backports.zstd >=1.0.0  # [py<313]

test:
  imports:
    - httpx2
  requires:
    - pip
    - click >=8.4.2
    - pygments 2.*
    - rich >=10,<16
  commands:
    - pip check
    - httpx2 --help

about:
  home: https://github.com/pydantic/httpx2
  summary: The next generation HTTP client.
  description: |
    HTTPX2 is a fully featured HTTP client library for Python. It includes an
    integrated command line client, has support for both HTTP/1.1 and HTTP/2,
    and provides both sync and async APIs.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  dev_url: https://github.com/pydantic/httpx2
  doc_url: https://httpx2.pydantic.dev

extra:
  recipe-maintainers:
    - bollwyvl
    - Kludex